spring:
  cloud:
    function:
      definition: numberConsumer
    stream:
      bindings:
        numberProducer-out-0:
          destination: first-topic
        numberConsumer-in-0:
          group: group
          destination: first-topic
          consumer:
            defaultRetryable: false
            retryableExceptions:
              java.lang.RuntimeException: true
              java.lang.IllegalStateException: false
            max-attempts: 8
            back-off-multiplier: 10
      kafka:
        bindings:
          numberConsumer-in-0:
            consumer:
              standard-headers:
              enableDlq: true
              dlqName: dlq
              dlq-partitions: 1
#logging:
#  level:
#    org:
#      springframework:
#        retry: debug